server:
  port: 8010
  # 应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-service
  mvc:
    log-request-details: true
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  web:
    resources:
      add-mappings: true
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
#        namespace: Public
  profiles:
    active: dev
logging:
  level:
    web: TRACE