server:
  port: 8010
  # 应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-service
  mvc:
    log-request-details: true
    # 如果没有找到请求地址，抛异常
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  web:
    resources:
      add-mappings: true
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
#        namespace: Public
#  resources:
#    add-mappings: false   # 关闭默认的静态资源路径映射
  profiles:
    active: dev
logging:
  level:
    web: TRACE