server:
  port: 8010
  # 应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
#        namespace: Public
  profiles:
    active: dev